# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:09
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import SalesPeople.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('contact_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField(verbose_name='Date and time of meeting')),
                ('proactive', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalesPeople.Company')),
                ('company_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesPeople.CompanyRepresentative')),
                ('sales_person',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Amount in Rands')),
                ('date_acquired', models.DateField(verbose_name='Date sale was acquired')),
                ('due_date', models.DateField(verbose_name='Date sale is due')),
                ('sale_completed', models.BooleanField(default=False)),
                ('unique_id',
                 models.CharField(blank=True, max_length=20, null=True, verbose_name='Optional unique reminder')),
                ('quote_number', models.CharField(default='MPT', max_length=10, verbose_name='Quote Number')),
                ('date_sale_completed',
                 models.DateField(blank=True, null=True, unique=True, verbose_name='Date of sale completion')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=SalesPeople.models.Company,
                                              to='SalesPeople.Company')),
                ('company_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesPeople.CompanyRepresentative')),
                ('meetings', models.ManyToManyField(blank=True, to='SalesPeople.Meeting')),
                ('sales_people', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProbability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.CharField(blank=True, default='Potential', max_length=10, null=True,
                                                 verbose_name='Sale Probability')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=10)),
                ('total_sales_amount', models.FloatField(default=0)),
                ('pending_sales_amount', models.FloatField(default=0)),
                ('total_sales_count', models.IntegerField(default=0)),
                ('pending_sales_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='Opportunity', max_length=12, null=True,
                                            verbose_name='Sale Status')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesPeople.CompanyRepresentative'),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_representative',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
