# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 11:51
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(
                    choices=[('Meeting', 'Meeting lekker'), ('Phone call', 'Phone call lekker'),
                             ('Email', 'Email lekker')], default='Meeting', max_length=20)),
                ('activity_type', models.CharField(choices=[('Making contact', 'Attempting connection'),
                                                            ('Establishing sale potential', 'Attempting qualification'),
                                                            ('Trying to make a sale', 'Attempting Sale')],
                                                   default='Making contact', max_length=50)),
                ('title', models.CharField(default='Speak to team leader for more details', max_length=32,
                                           verbose_name='Activity title')),
                ('description', models.CharField(max_length=512, null=True, verbose_name='Activity description')),
                ('activity_start_date', models.DateTimeField(verbose_name='Activity start date and time')),
                ('activity_completion_date', models.DateTimeField(verbose_name='Activity completion date and time')),
                ('activity_end_date', models.DateTimeField(verbose_name='Activity end date and time')),
                ('completed', models.BooleanField(default=False, verbose_name='Submitted completed')),
                ('verified_completed',
                 models.BooleanField(default=False, verbose_name='Verified complete by team leader')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('qualified', models.BooleanField(default=False, verbose_name='Qualified')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('contact_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal activities', models.ManyToManyField(to='SalesPeople.Activity')),
                ('Sales Person Goal set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                            to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0, verbose_name='Value in Rands')),
                ('date_acquired', models.DateField(verbose_name='Date sale was acquired')),
                ('due_date', models.DateField(verbose_name='Date sale is due')),
                (
                    'date_sale_completed',
                    models.DateField(blank=True, null=True, verbose_name='Date of sale completion')),
                ('probability', models.CharField(
                    choices=[('Blue Bird', 'Blue bird penis'), ('Probable', 'Probable penis'),
                             ('Forecast', 'Forecast penis')], default='Probable', max_length=12,
                    verbose_name='Sale Probability')),
                ('status', models.CharField(
                    choices=[('Abandoned', 'Abandoned penis'), ('Lost', 'Lost penis'), ('Budget', 'Budget penis'),
                             ('Won', 'Won penis'), ('In progress', 'In progress penis')], default='In progress',
                    max_length=12, verbose_name='Sale Status')),
                ('sale_completed', models.BooleanField(default=False, verbose_name='Sale closed')),
                ('unique_id',
                 models.CharField(blank=True, max_length=20, null=True, verbose_name='Optional unique reminder')),
                ('sale_description', models.CharField(max_length=256, null=True, verbose_name='Description')),
                ('quote_number', models.CharField(default='MPT', max_length=10, verbose_name='Quote Number')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='SalesPeople.Company')),
                ('company_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesPeople.CompanyRepresentative')),
                ('consultant',
                 models.ManyToManyField(blank=True, related_name='consultant', to='SalesPeople.CompanyRepresentative')),
                ('consulting_company',
                 models.ManyToManyField(related_name='consultant_company', to='SalesPeople.Company')),
                ('meetings', models.ManyToManyField(blank=True, to='SalesPeople.Activity')),
                ('other_salespeople',
                 models.ManyToManyField(related_name='secondary_salespeople', to=settings.AUTH_USER_MODEL)),
                ('prime_salesperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                        related_name='prime_salesperson', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader', models.BooleanField(default=False, verbose_name='Team Leader')),
                ('contact_number', models.CharField(max_length=10)),
                ('total_sales_amount', models.FloatField(default=0)),
                ('pending_sales_amount', models.FloatField(default=0)),
                ('total_sales_count', models.IntegerField(default=0)),
                ('pending_sales_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30, null=True, verbose_name='Branch name')),
                ('Team Leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='team_leader_user', to=settings.AUTH_USER_MODEL)),
                ('Team Sales', models.ManyToManyField(to='SalesPeople.Sale')),
                ('Team members', models.ManyToManyField(related_name='team_member_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='Company Representatives',
            field=models.ManyToManyField(to='SalesPeople.CompanyRepresentative'),
        ),
        migrations.AddField(
            model_name='company',
            name='sales_representative',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='SalesPeople.Company'),
        ),
        migrations.AddField(
            model_name='activity',
            name='company_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='SalesPeople.CompanyRepresentative'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
