# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SalesPeople', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='last_name',
        ),
        migrations.AddField(
            model_name='salesperson',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='sales_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='sales_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_people',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
