# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:10
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SalesPeople', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_probability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='SalesPeople.SaleProbability'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to='SalesPeople.SaleStatus'),
        ),
    ]
