# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SalesPeople', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='Goal description',
            field=models.CharField(default='Self-explanatory', max_length=256),
        ),
        migrations.AddField(
            model_name='goal',
            name='Goal title',
            field=models.CharField(default='Make a million dollars', max_length=64),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(choices=[('Meeting', 'Meeting'), ('Phone call', 'Phone call'), ('Email', 'Email')],
                                   default='Meeting', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_completion_date',
            field=models.DateTimeField(verbose_name='Task completion date and time'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_end_date',
            field=models.DateTimeField(verbose_name='Task end date and time'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_start_date',
            field=models.DateTimeField(verbose_name='Task start date and time'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Making contact', 'Making contact'),
                                            ('Establishing sale potential', 'Establishing sale potential'),
                                            ('Trying to make a sale', 'Trying to make a sale')],
                                   default='Making contact', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=512, null=True, verbose_name='Task description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, default='Speak to team leader for more details', max_length=32,
                                   verbose_name='Task title'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='probability',
            field=models.CharField(
                choices=[('Blue Bird', 'Blue bird'), ('Probable', 'Probable'), ('Forecast', 'Forecast')],
                default='Probable', max_length=12, verbose_name='Sale Probability'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(
                choices=[('Abandoned', 'Abandoned'), ('Lost', 'Lost'), ('Budget', 'Budget'), ('Won', 'Won'),
                         ('In progress', 'In progress')], default='In progress', max_length=12,
                verbose_name='Sale Status'),
        ),
    ]
