# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 12:50
from __future__ import unicode_literals

import datetime

import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('SalesPeople', '0003_auto_20170718_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 12, 50, 25, 932721, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='Date added',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 12, 50, 25, 930133, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
