# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesPeople', '0003_auto_20170502_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='email_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
