# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 12:50
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SalesPeople', '0004_auto_20170718_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='Date added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
