# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesPeople', '0004_salesperson_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='salesperson',
            name='user',
        ),
    ]
