# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 14:01
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SalesPeople', '0005_auto_20170718_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='company',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='date_acquired',
        ),
        migrations.RemoveField(
            model_name='salesteam',
            name='date_added',
        ),
        migrations.AddField(
            model_name='activity',
            name='Date added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='company',
            name='Date added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='Date added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='Date added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='salesteam',
            name='Date added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Making contact', 'Making contact'), ('Establishing sale potential',
                                                                                   'Establishing sale poSalesTeam.objects.filter(team_leader=users_salesperson.id)tential'),
                                            ('Trying to make a sale', 'Trying to make a sale')],
                                   default='Making contact', max_length=50),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='Date added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
