# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SalesPeople', '0006_salesperson_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='email_address',
        ),
        migrations.AddField(
            model_name='salesperson',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
