# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesPeople', '0008_auto_20170622_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sales_representative',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
