# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SalesPeople', '0009_auto_20170622_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount in Rands'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Optional unique reminder'),
        ),
    ]
