# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SalesPeople', '0012_auto_20170718_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesteam',
            name='Team members',
        ),
        migrations.AddField(
            model_name='salesteam',
            name='team_members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
