# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 06:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SalesPeople', '0013_auto_20170703_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='SalesPeople.SaleStatus'),
        ),
    ]
