# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('SalesPeople', '0014_auto_20170703_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='status',
        ),
    ]
