# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesPeople', '0014_auto_20170719_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesteam',
            old_name='Team Sales',
            new_name='team_sales',
        ),
    ]
