# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 07:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesPeople', '0015_auto_20170719_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Making contact', 'Making contact'), ('Establishing sale potential', 'Establishing sale potential'), ('Trying to make a sale', 'Trying to make a sale')], default='Making contact', max_length=50),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_member_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
