# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('SalesPeople', '0015_remove_sale_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleProbability',
        ),
        migrations.DeleteModel(
            name='SaleStatus',
        ),
    ]
