# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SalesPeople', '0016_auto_20170703_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Opportunity', max_length=12, verbose_name='Sale Status')),
            ],
        ),
    ]
