# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SalesPeople', '0017_salestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to='SalesPeople.SaleStatus'),
        ),
    ]
