# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SalesPeople', '0018_sale_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProbability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.CharField(default='Potential', max_length=10)),
            ],
        ),
    ]
