# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SalesPeople', '0020_sale_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
