# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SalesPeople', '0021_meeting_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleprobability',
            name='probability',
            field=models.CharField(default='Potential', max_length=10, verbose_name='Sale Probability'),
        ),
    ]
